---
title: OECD Health Care Utilization Data
author: Vid Bijelic, Nick Barrowman
date: '`r strftime(Sys.time(),format="%d-%b-%Y at %H:%M")`'
output: 
  word_document:
    reference_docx: 'R:/CRU Epibiostat/Rmarkdown knitr/templateLandscape8ptArialNarrowMargins.docx'
---

```{r setup, include=FALSE}
# Set knitr options: 
knitr::opts_chunk$set(echo = FALSE,comment="",dpi=72*8,fig.width=10,fig.height=6.2)

require(ggplot2)
require(pander)
```

```{r}
source("root_source.R")
```

# Preliminary descriptives

The data set has `r nrow(dat)` rows and `r ncol(dat)` columns.

```{r}
# Make pander tables as wide as necessary
panderOptions('table.split.table', Inf)
panderOptions('table.split.cells', Inf)
```

## Variables
```{r}
d <- dat[!duplicated(dat$var),]
rownames(d) <- NULL

pander(d[,c("var","variable")])
```

## Country by variable

```{r}
pander(table(dat$country,dat$var))
```

## Records by year

```{r echo=FALSE}

datNorthAm <- dat[dat$country %in% c("Canada","United States",
                                     "Japan",
                                     "China (People's Republic of)",
                                     "Korea") &
                    dat$variable=="Immunisation: Hepatitis B",]

pander(cbind(table(dat$year)),citation="Records by year")


```

# Graphs

## Graph - Hepatitis B Immunisation in North America and East Asia

```{r echo=FALSE}



p <- ggplot(datNorthAm, aes(x=year, y=value, color=country)) +
  geom_point()

p <- p + stat_smooth(aes(colour = country),
              method = "loess", 
              formula = y ~ x, 
              se = TRUE)

p + ggtitle("Hepatitis B Immunisation") +
  theme(plot.title = element_text(lineheight=.8, face="bold")) +
  xlab("Year") + ylab("% Imunized Children")

```

## Graph - Immunisation of Influenza in North America and East Asia

```{r echo=FALSE}

datNorthAm <- dat[dat$country %in% c("Canada","United States",
                                     "Japan",
                                     "China (People's Republic of)",
                                     "Korea") &
                    dat$variable=="Immunisation: Influenza",]


p <- ggplot(datNorthAm, aes(x=year, y=value, color=country)) +
  geom_point()

p <- p + stat_smooth(aes(colour = country),
              method = "loess", 
              formula = y ~ x, 
              se = TRUE)

p + ggtitle("Immunisation of Influenza") +
  theme(plot.title = element_text(lineheight=.8, face="bold")) +
  xlab("Year") + ylab("% Imunized Children")

```


